### ISSUE TITLE
Connect metrics in gitops deploys to grafana

### ISSUE THREAD

**Issue by willscott** [filecoin-project/storetheindex#304] opened 2022-03-31 17:04 UTC
we don't currently have piping for collecting metrics from storetheindex in the deployment managed by gitops and tracking it somewhere observable.

**Comment by masih** [comment] 2022-04-15 12:55
Duplicate of https://github.com/filecoin-project/storetheindex/issues/372
Note that metrics are collected from instances running in our own AWS account. they are just not forwarded to PL grafana.

Closing; please feel free to reopen if I missed anything.

**Closed by masih** 2022-04-15 12:55 UTC
Labels: infra
