### ISSUE TITLE
endpoint to get Indexer CIDs count

### ISSUE THREAD

**Issue by honghaoq** [filecoin-project/storetheindex#506] opened 2022-05-22 23:10 UTC
We are working on revamping cid.contact, which would be the landing home page for content routing. We'd like to expose core indexer metrics there, such as index CIDs volume and provider counts. Right now we have endpoint /providers, we'd need /stats endpoint for CIDs count

**Comment by willscott** [comment] 2022-06-13 17:44
duplicate of #406

**Closed by willscott** 2022-06-13 17:44 UTC
Labels: low priority
